openapi: 3.0.3
info:
  title: Filocitas API
  version: 1.0.0
  description: Combined OpenAPI specification for Filocitas administrative and public endpoints.
servers:
  - url: /api
tags:
  - name: Admin
    description: Administrative endpoints that require privileged access.
  - name: Public
    description: General purpose endpoints for accessing public Filocitas data.
  - name: Metrics
    description: Publicly accessible counters that expose aggregate data.
paths:
  /admin/quotes:
    $ref: 'admin-api.yaml#/paths/~1admin~1quotes'
  /admin/quote:
    $ref: 'admin-api.yaml#/paths/~1admin~1quote'
  /admin/quote/{id}:
    $ref: 'admin-api.yaml#/paths/~1admin~1quote~1{id}'
  /admin/ping:
    $ref: 'admin-api.yaml#/paths/~1admin~1ping'
  /admin/authors/quotes/limit/{limit}:
    $ref: 'admin-api.yaml#/paths/~1admin~1authors~1quotes~1limit~1{limit}'
  /public/quote/random:
    $ref: 'public-api.yaml#/paths/~1public~1quote~1random'
  /public/quote/{id}:
    $ref: 'public-api.yaml#/paths/~1public~1quote~1{id}'
  /public/quote/{id}/like:
    $ref: 'public-api.yaml#/paths/~1public~1quote~1{id}~1like'
  /public/authors:
    $ref: 'public-api.yaml#/paths/~1public~1authors'
  /public/author/{id}:
    $ref: 'public-api.yaml#/paths/~1public~1author~1{id}'
  /public/author/{id}/quotes:
    $ref: 'public-api.yaml#/paths/~1public~1author~1{id}~1quotes'
  /public/tags:
    $ref: 'public-api.yaml#/paths/~1public~1tags'
  /public/tags/count:
    $ref: 'public-api.yaml#/paths/~1public~1tags~1count'
  /public/tag/{name}/quotes:
    $ref: 'public-api.yaml#/paths/~1public~1tag~1{name}~1quotes'
  /public/quotes/count:
    $ref: 'public-api.yaml#/paths/~1public~1quotes~1count'
  /public/authors/count:
    $ref: 'public-api.yaml#/paths/~1public~1authors~1count'
  /public/quotes/top/{limit}:
    $ref: 'public-api.yaml#/paths/~1public~1quotes~1top~1{limit}'
