openapi: 3.0.3
info:
  title: Filocitas Public API
  version: 1.0.0
  description: Public API for retrieving quotes and authors for Filocitas.
servers:
  - url: /api
paths:
  /public/quote/random:
    get:
      tags:
        - Public
      summary: Get a random quote
      operationId: getRandomQuote
      responses:
        '200':
          description: Random quote retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '204':
          description: No quote available
  /public/quote/{id}:
    get:
      tags:
        - Public
      summary: Get quote by id
      operationId: getQuoteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quote found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Quote not found
  /public/quote/{id}/like:
    get:
      tags:
        - Public
      summary: Get quote likes by id
      operationId: getQuoteLikes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quote likes retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteLikesResponse'
        '404':
          description: Quote not found
    post:
      tags:
        - Public
      summary: Like quote by id
      operationId: likeQuote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quote liked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteLikesResponse'
        '404':
          description: Quote not found
  /public/authors:
    get:
      tags:
        - Public
      summary: Get all authors
      operationId: getAuthors
      responses:
        '200':
          description: Authors returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '204':
          description: No authors available
  /public/author/{id}:
    get:
      tags:
        - Public
      summary: Get author by id
      operationId: getAuthorById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Author found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Author not found
  /public/author/{id}/quotes:
    get:
      tags:
        - Public
      summary: Get quotes written by the author
      operationId: getQuotesByAuthor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quotes retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '204':
          description: No quotes found
  /public/tags:
    get:
      tags:
        - Public
      summary: Get all tags
      operationId: getTags
      responses:
        '200':
          description: Tags retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '204':
          description: No tags available
  /public/tag/{name}/quotes:
    get:
      tags:
        - Public
      summary: Get quotes by tag
      operationId: getQuotesByTag
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Quotes retrieved for the given tag
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '204':
          description: No quotes found for the given tag
  /quotes/top/{limit}:
    get:
      tags:
        - Public
      summary: Get top quotes by likes
      operationId: getTopQuotes
      parameters:
        - name: limit
          in: path
          required: true
          schema:
            type: integer
            enum: [3, 5, 10, 25, 50]
      responses:
        '200':
          description: Quotes retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuoteWithLikes'
        '204':
          description: No quotes available for the requested limit
        '400':
          description: Invalid limit supplied
components:
  schemas:
    Quote:
      type: object
      required:
        - id
        - quote
        - author
      properties:
        id:
          type: string
          format: uuid
        quote:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        tags:
          type: array
          description: List of thematic tags associated with the quote.
          items:
            type: string
    Author:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    QuoteRequest:
      type: object
      required:
        - quote
        - author
      properties:
        quote:
          type: string
          description: The textual content of the quote.
        author:
          type: string
          description: The display name of the quote author.
        author_wikipedia:
          type: string
          format: uri
          description: Optional link to the author's Wikipedia page.
        work:
          type: string
          description: The work where the quote originated.
        year:
          type: integer
          format: int32
          description: The year the quote was created or published. Negative numbers represent BCE years.
        tags:
          type: array
          description: Thematic tags associated with the quote.
          items:
            type: string
        century:
          type: string
          description: The century associated with the quote, e.g., "-5".
    QuoteLikesResponse:
      type: object
      required:
        - likes
      properties:
        likes:
          type: integer
          format: int64
          description: Total likes registered for the quote.
    QuoteWithLikes:
      type: object
      required:
        - quote
        - likes
      properties:
        quote:
          $ref: '#/components/schemas/Quote'
        likes:
          type: integer
          format: int64
          description: Number of likes associated with the quote.
    AuthorInput:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
