openapi: 3.0.3
info:
  title: Filocitas Public API
  version: 1.0.0
  description: Public API for retrieving quotes and authors for Filocitas.
servers:
  - url: /api
paths:
  /public/quote/random:
    get:
      tags:
        - Public
      summary: Get a random quote
      operationId: getRandomQuote
      responses:
        '200':
          description: Random quote retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '204':
          description: No quote available
  /public/quote/{id}:
    get:
      tags:
        - Public
      summary: Get quote by id
      operationId: getQuoteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quote found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Quote not found
  /public/authors:
    get:
      tags:
        - Public
      summary: Get all authors
      operationId: getAuthors
      responses:
        '200':
          description: Authors returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '204':
          description: No authors available
  /public/author/{id}:
    get:
      tags:
        - Public
      summary: Get author by id
      operationId: getAuthorById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Author found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Author not found
  /public/author/{id}/quotes:
    get:
      tags:
        - Public
      summary: Get quotes written by the author
      operationId: getQuotesByAuthor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quotes retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '204':
          description: No quotes found
  /public/tags:
    get:
      tags:
        - Public
      summary: Get all tags
      operationId: getTags
      responses:
        '200':
          description: Tags retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '204':
          description: No tags available
components:
  schemas:
    Quote:
      type: object
      required:
        - id
        - text
        - author
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        tags:
          type: array
          description: List of thematic tags associated with the quote.
          items:
            type: string
    Author:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    QuoteRequest:
      type: object
      required:
        - text
        - author
      properties:
        text:
          type: string
        author:
          $ref: '#/components/schemas/AuthorInput'
    AuthorInput:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
