### Create multiple quotes
POST https://template-api-render.onrender.com/api/admin/quotes
Content-Type: application/json
Accept: application/json

[
  {
    "quote": "Although they are only breath, words which I command are immortal.",
    "author": "Safo",
    "author_wikipedia": "https://es.wikipedia.org/wiki/Safo",
    "work": "Fragmentos",
    "year": -600,
    "tags": [
      "poesía",
      "legado",
      "lenguaje"
    ],
    "century": "-6"
  },
  {
    "quote": "Ignorance leads to fear, fear leads to hate, and hate leads to violence.",
    "author": "Averroes",
    "author_wikipedia": "https://es.wikipedia.org/wiki/Averroes",
    "work": "El discurso decisivo",
    "year": 1179,
    "tags": [
      "conocimiento",
      "miedo",
      "ética"
    ],
    "century": "12"
  }
]
