### Create Pitágoras quote
POST https://template-api-render.onrender.com/api/admin/quote
Content-Type: application/json
Accept: application/json

{
  "quote": "No perturbes la armonía del alma: vive según el orden y la medida que rigen el universo.",
  "author": "Pitágoras",
  "author_wikipedia": "https://es.wikipedia.org/wiki/Pit%C3%A1goras",
  "work": "Versos áureos",
  "year": -500,
  "tags": [
    "armonía",
    "alma",
    "cosmos",
    "orden"
  ],
  "century": "-5"
}
