apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api-deployment
  annotations:
    commitID: "533bacd43bad76cbf7cd749d8350bd4624308788"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-api
    spec:
      containers:
        - name: template-api
          image: 'xavelo/template-api-spring-boot:533bacd43bad76cbf7cd749d8350bd4624308788'
          ports:
            - containerPort: 80
