apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api-deployment
  annotations:
    commitID: "20c022ab43550d7c15fc3a71a2057042553624fd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: template-api
    spec:
      containers:
        - name: template-api
          image: 'xavelo/template-api-spring-boot:20c022ab43550d7c15fc3a71a2057042553624fd'
          ports:
            - containerPort: 80
